"""gen_setting_table.py: regenerate src/ngpu_backend_dll/ngpu_setting_table.inc from the vendored backend.

The vendored backend (src/native_gpu_xlat) has no registered cvars: every setting is an accessor-only copy,
`T& FLAGS_<name>_storage_() { static T s = PluginX("<name>", default); return s; }`, read from the runtime registry
ONCE. ngpu_backend.dll exposes those copies by name (NgpuBackendGetSetting / NgpuBackendSetSetting) so a host can
push a live change in (e.g. ng2_fov_k) and read a value the backend computes out (e.g. ng2_uw_mode). Re-run this after
re-vendoring; it enumerates the definitions, so a new setting cannot be missed.

  python tools/native_gpu/gen_setting_table.py
"""
import os
import re

ROOT = os.path.join(os.path.dirname(__file__), '..', '..', 'src')
XLAT = os.path.join(ROOT, 'native_gpu_xlat')
OUT = os.path.join(ROOT, 'ngpu_backend_dll', 'ngpu_setting_table.inc')
PAT = re.compile(r'^(bool|int32_t|double|std::string)& FLAGS_([a-z0-9_]+)_storage_\(\) \{', re.M)
KIND = {'bool': 'kBool', 'int32_t': 'kInt', 'double': 'kDouble', 'std::string': 'kString'}

found = {}
for dirpath, _, files in os.walk(XLAT):
    for f in files:
        if not f.endswith('.cpp'):
            continue
        text = open(os.path.join(dirpath, f), encoding='utf-8', errors='replace').read()
        for m in PAT.finditer(text):
            found.setdefault(m.group(2), m.group(1))

lines = ['// GENERATED by tools/native_gpu/gen_setting_table.py - do not edit. %d settings.' % len(found), '']
for name, t in sorted(found.items()):
    lines.append('%s& FLAGS_%s_storage_();' % (t, name))
lines += ['', '#define NGPU_SETTING_TABLE \\']
for name, t in sorted(found.items()):
    lines.append('  {"%s", SettingKind::%s, reinterpret_cast<void* (*)()>(&FLAGS_%s_storage_)}, \\' % (name, KIND[t], name))
lines.append('')
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines))
print('wrote %s: %d settings' % (OUT, len(found)))
