#!/usr/bin/env python3
"""Generate the Xenos->native coverage census DENOMINATOR from the SDK headers.

The census's whole value is that its denominator is the FIXED Xenos hardware
command surface, extracted from the SDK's own enums rather than hand-listed - so
it stays complete as the SDK changes and no game can enlarge it. This script is
the extractor. Output: native_gpu_census_subjects.inc, a list of
    NGPU_CENSUS_SUBJECT(Kind, id, "name")
lines consumed by native_gpu_census.cpp.

Surfaces taken (this set is itself an assumption - see the provenance block the
census prints; anything a game exercises that is off this list is flagged
OFF-CENSUS at runtime, which is how an incomplete set is discovered):
  - PM4 Type3 opcodes         xenos.h        enum Type3Opcode
  - shader ISA                ucode.h        AluVector/AluScalar/Fetch/ControlFlow
  - texture/vertex/rt/endian/primitive formats  xenos.h  (the format enums)
  - registers                 register_table.inc  XE_GPU_REGISTER(index,type,name)
"""
import re, sys, os

SDK = r"C:\Users\renoi\ClaudeCode\Fable 2 Recompile Xbox\RexBlue\win-amd64\include\rex\graphics"
XENOS = os.path.join(SDK, "xenos.h")
UCODE = os.path.join(SDK, "format", "ucode.h")
REGTBL = os.path.join(SDK, "register_table.inc")
OUT = os.path.join(os.path.dirname(__file__), "..", "..", "src", "native_gpu_census_subjects.inc")


def read(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


def parse_enum(text, enum_name):
    """Return [(member_name, value), ...] for `enum [class] NAME [: type] { ... }`,
    tracking implicit auto-increment and honoring explicit = values (hex/dec)."""
    m = re.search(r"enum\s+(?:class\s+)?" + re.escape(enum_name) + r"\b[^\{]*\{", text)
    if not m:
        raise SystemExit(f"enum {enum_name} not found")
    i = m.end()
    depth = 1
    body = []
    while i < len(text) and depth:
        c = text[i]
        if c == "{": depth += 1
        elif c == "}": depth -= 1
        if depth: body.append(c)
        i += 1
    body = "".join(body)
    body = re.sub(r"//[^\n]*", "", body)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    out, val = [], 0
    for part in body.split(","):
        part = part.strip()
        if not part:
            continue
        mm = re.match(r"^([A-Za-z_]\w*)\s*(?:=\s*(.+))?$", part)
        if not mm:
            continue
        name, expr = mm.group(1), mm.group(2)
        if expr is not None:
            expr = expr.strip()
            try:
                val = int(expr, 0)
            except ValueError:
                # reference to a prior member (e.g. kFoo = kBar) - resolve
                prior = dict(out)
                val = prior.get(expr)
                if val is None:
                    continue
        out.append((name, val))
        val += 1
    return out


def emit_enum(lines, text, enum_name, kind, seen_ids):
    members = parse_enum(text, enum_name)
    n = 0
    for name, val in members:
        key = (kind, val)
        if key in seen_ids:      # sparse enums can repeat a value as an alias; keep first
            continue
        seen_ids.add(key)
        lines.append(f'NGPU_CENSUS_SUBJECT({kind}, 0x{val:X}, "{name}")')
        n += 1
    return n


def emit_registers(lines):
    """register_table.inc: XE_GPU_REGISTER(index, type, name). The 2280
    shader-constant-MEMORY registers share one upload mechanism, so they are
    collapsed to 4 block subjects; the ~1160 real control registers stay
    individual. Documented in the provenance the census prints."""
    text = read(REGTBL)
    rows = re.findall(r"XE_GPU_REGISTER\(\s*(0x[0-9A-Fa-f]+|\d+)\s*,\s*\w+\s*,\s*(\w+)\s*\)", text)
    n, collapsed = 0, {}
    for idx, name in rows:
        val = int(idx, 0)
        if name.startswith("SHADER_CONSTANT_"):
            # bucket: ALU (SHADER_CONSTANT_000_X..), FETCH, BOOL, LOOP, FLUSH
            if name.startswith("SHADER_CONSTANT_FETCH"): block = "FETCH"
            elif name.startswith("SHADER_CONSTANT_BOOL"): block = "BOOL"
            elif name.startswith("SHADER_CONSTANT_LOOP"): block = "LOOP"
            elif name.startswith("SHADER_CONSTANT_FLUSH"): block = "FLUSH"
            else: block = "ALU"
            if block not in collapsed:
                collapsed[block] = val   # first (base) index represents the block
            continue
        lines.append(f'NGPU_CENSUS_SUBJECT(Register, 0x{val:X}, "{name}")')
        n += 1
    for block, base in sorted(collapsed.items(), key=lambda kv: kv[1]):
        lines.append(f'NGPU_CENSUS_SUBJECT(Register, 0x{base:X}, "SHADER_CONSTANT_{block}_BLOCK")')
        n += 1
    return n, len(collapsed)


def main():
    xenos = read(XENOS)
    ucode = read(UCODE)
    lines = ["// GENERATED by tools/native_gpu/gen_census.py - do not edit.",
             "// The Xenos hardware command surface, extracted from the SDK enums.",
             ""]
    counts = {}
    seen = set()

    counts["PM4 opcodes"] = emit_enum(lines, xenos, "Type3Opcode", "Pm4Opcode", seen)

    counts["ALU vector ops"] = emit_enum(lines, ucode, "AluVectorOpcode", "ShaderAluVector", seen)
    counts["ALU scalar ops"] = emit_enum(lines, ucode, "AluScalarOpcode", "ShaderAluScalar", seen)
    counts["fetch ops"] = emit_enum(lines, ucode, "FetchOpcode", "ShaderFetch", seen)
    counts["control-flow ops"] = emit_enum(lines, ucode, "ControlFlowOpcode", "ShaderControlFlow", seen)

    # Format enums - names confirmed by the format recon agent; parse_enum raises
    # if a name is wrong, which is the signal to correct it here.
    for enum_name, kind in [("TextureFormat", "TextureFormat"),
                            ("VertexFormat", "VertexFormat"),
                            ("ColorRenderTargetFormat", "ColorRtFormat"),
                            ("DepthRenderTargetFormat", "DepthRtFormat"),
                            ("Endian", "Endian"),
                            ("PrimitiveType", "PrimitiveType")]:
        try:
            counts[enum_name] = emit_enum(lines, xenos, enum_name, kind, seen)
        except SystemExit as e:
            counts[enum_name] = f"NOT FOUND ({e})"

    reg_n, reg_collapsed = emit_registers(lines)
    counts["registers (control)"] = reg_n
    counts[f"registers (constant blocks collapsed)"] = reg_collapsed

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print("Census denominator written to", os.path.normpath(OUT))
    total = 0
    for k, v in counts.items():
        print(f"  {k:36s} {v}")
        if isinstance(v, int):
            total += v
    print(f"  {'TOTAL subjects':36s} {total}")


if __name__ == "__main__":
    main()
