"""gen_gpu_cvars.py BEFORE.tsv AFTER.tsv: write src/fable2_gpu_cvars.cpp - the exe's own registration of every cvar
rexgpu-xenos.dll registered (2026-09-28, the DLL's removal; NG2 did the same in 098510c).

Input: two dumps of the live settings registry from one run (FABLE2_CVARDUMP=<prefix>, fable2_app.h): before and after
the plugin library loads. The difference is exactly what the SHIPPED DLL registers - name, type, category, default,
range, allowed values, lifecycle, description - so no source branch has to be guessed. The entries are registered
through rex::cvar::RegisterFlag directly (not REXCVAR_DEFINE), because the vendored backend already defines
FLAGS_<name>_storage_() accessors for 100 of them that read the registry by name; they keep working unchanged.
"""
import csv
import os
import sys

before, after = sys.argv[1], sys.argv[2]
OUT = os.path.join(os.path.dirname(__file__), "..", "..", "src", "fable2_gpu_cvars.cpp")


def load(p):
    return {r[0]: r for r in csv.reader(open(p, encoding="utf-8", errors="replace"), delimiter="\t") if r}


b, a = load(before), load(after)
rows = [a[k] for k in sorted(a) if k not in b]


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


lines = []
for name, typ, cat, life, default, mn, mx, allowed, desc in (r + [""] * (9 - len(r)) for r in rows):
    lines.append("    {%s, %s, %s, %s, %s, %s, %s, %s, %s}," % (
        cstr(name), typ, cstr(cat), life, cstr(default),
        mn if mn else "kNoBound", mx if mx else "kNoBound", cstr(allowed), cstr(desc)))

src = '''// GENERATED by tools/native_gpu/gen_gpu_cvars.py from the settings registry of the shipped rexgpu-xenos.dll (sha
// 476447cad811): before/after dumps of one run with FABLE2_CVARDUMP. Do not edit by hand - regenerate.
//
// rexgpu-xenos.dll is no longer loaded (2026-09-28). Everything it registered is registered here instead, with the same
// type, default, range, allowed values, lifecycle and description, so the settings file, the F10 menu, the startup
// tuning and the vendored backend's by-name readers (FLAGS_*_storage_ -> Plugin*/Refresh*) see exactly what they saw.
#include <charconv>
#include <cstdlib>
#include <deque>
#include <limits>
#include <string>
#include <string_view>

#include <rex/cvar.h>

namespace {
constexpr double kNoBound = std::numeric_limits<double>::quiet_NaN();
struct Def {
  const char* name;
  int type;        // rex::cvar::FlagType
  const char* category;
  int lifecycle;   // rex::cvar::Lifecycle
  const char* def;
  double min, max; // kNoBound = none
  const char* allowed;   // '|'-separated, empty = any
  const char* desc;
};
const Def kDefs[] = {
%s
};

std::string NormalizeBool(std::string_view v) {
  std::string s(v);
  for (char& c : s) c = char(std::tolower(static_cast<unsigned char>(c)));
  return (s == "true" || s == "1" || s == "yes" || s == "on") ? "true" : "false";
}

struct Registrations {
  std::deque<std::string> values;   // one live value per entry (stable addresses)
  Registrations() {
    for (const Def& d : kDefs) {
      values.emplace_back(d.def);
      std::string* value = &values.back();
      const auto type = rex::cvar::FlagType(d.type);
      rex::cvar::FlagEntry e;
      e.name = d.name;
      e.type = type;
      e.category = d.category;
      e.description = d.desc;
      e.lifecycle = rex::cvar::Lifecycle(d.lifecycle);
      e.default_value = d.def;
      if (d.min == d.min) e.constraints.min = d.min;
      if (d.max == d.max) e.constraints.max = d.max;
      for (std::string_view rest = d.allowed; !rest.empty();) {
        const size_t bar = rest.find('|');
        e.constraints.allowed_values.emplace_back(rest.substr(0, bar));
        rest = bar == std::string_view::npos ? std::string_view() : rest.substr(bar + 1);
      }
      e.setter = [value, type](std::string_view v) {
        switch (type) {
          case rex::cvar::FlagType::Boolean: *value = NormalizeBool(v); return true;
          case rex::cvar::FlagType::Int32:
          case rex::cvar::FlagType::Int64: {
            long long x = 0;
            auto [p, ec] = std::from_chars(v.data(), v.data() + v.size(), x);
            if (ec != std::errc()) return false;
            *value = std::to_string(x);
            return true;
          }
          case rex::cvar::FlagType::Uint32:
          case rex::cvar::FlagType::Uint64: {
            unsigned long long x = 0;
            auto [p, ec] = std::from_chars(v.data(), v.data() + v.size(), x);
            if (ec != std::errc()) return false;
            *value = std::to_string(x);
            return true;
          }
          case rex::cvar::FlagType::Double: {
            std::string s(v);
            char* end = nullptr;
            std::strtod(s.c_str(), &end);
            if (end == s.c_str()) return false;
            *value = s;
            return true;
          }
          default: *value = std::string(v); return true;
        }
      };
      e.getter = [value] { return *value; };
      e.command_callback = [](std::string_view) {};
      rex::cvar::RegisterFlag(std::move(e));
    }
  }
};
Registrations g_registrations;
}  // namespace
''' % "\n".join(lines)
open(OUT, "w", encoding="utf-8", newline="\n").write(src)
print("wrote %s: %d cvars" % (os.path.normpath(OUT), len(rows)))
