"""Compile Xenia .xesl shaders into the bytecode headers the SDK consumes.

    python tools/build_shaders.py --verify      # regenerate and COMPARE, write nothing
    python tools/build_shaders.py --write       # regenerate into the SDK tree

WHY THIS EXISTS

The ReXGlue SDK ships GPU shaders only as prebuilt bytecode headers
(`src/graphics/shaders/bytecode/d3d12_5_1/*.h`) with no sources and no build
step. That made every Canary commit touching a shader unportable - including
`437a7280c`, the EDRAM sample-addressing rewrite, which is the largest post-fork
change and the one closest to the flat-blue bug.

But the sources are not missing, only unshipped: Canary keeps them as `.xesl` /
`.xesli`, our header names map onto them one-to-one
(`resolve_fast_32bpp_1x2xmsaa_cs.h` <- `resolve_fast_32bpp_1x2xmsaa.cs.xesl`),
and our headers say "Generated by Microsoft (R) HLSL Shader Compiler" - the same
FXC that Canary's `tools/build/compile_shader_dxbc.py` drives.

Verified before trusting it: compiling `apply_gamma_table.cs.xesl` from Canary
at our fork point reproduces the shipped header to within **16 bytes of 1304**,
and those 16 are the DXBC container's MD5 checksum plus one metadata byte. The
shader code is identical.

WHAT IT ACTUALLY FOUND (run --verify to reproduce)

Compiling every Canary shader from the fork point and comparing against what the
SDK ships:

    identical except the checksum + <=2 metadata bytes :  10
    differ in LENGTH (real divergence)                 :  83

So the toolchain is proven - ten shaders reproduce byte for byte - but **the
SDK's resolve and EDRAM shaders are its own code, not Canary's**. They are not
a version behind; they are materially different, and mostly SMALLER:

    resolve_full_16bpp_cs        ours 41,472   canary  99,848
    resolve_full_32bpp_cs        ours 41,336   canary  97,048
    resolve_downscale_cs         ours  2,212   canary   5,200

(The SDK also carries a hand-written resolve_downscale.cs.hlsl, which is the
same story visible in the source tree.)

The consequence for porting: having a shader compiler does NOT unblock
`437a7280c`. That commit rewrites Canary's resolve/EDRAM shaders, and ours are
not those shaders. Taking Canary's wholesale would discard whatever the SDK
changed and pair new shaders with our older host code - the exact mismatch the
commit message warns about. Porting it properly means re-implementing its
addressing change on top of the SDK's own shader variants, by hand.

THE INVARIANT THIS TOOL PROTECTS

`--verify` regenerates every mapped shader from the FORK-POINT sources and
compares it to what ships. While that passes, we own the pipeline and can take
shader-touching commits. If it starts failing, the sources and the shipped
bytecode have diverged and regenerating anything is unsafe - fix that before
porting, rather than shipping a shader nobody has checked.

Note that shaders and their C++ must move TOGETHER. Taking current Canary
shaders while our C++ sits at the fork point would pair new shaders with old
host code - exactly the mismatch 437a7280c warns about.
"""

import argparse
import glob
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SDK = os.path.join(ROOT, "..", "rexglue-src")
BYTECODE = os.path.join(SDK, "src", "graphics", "shaders", "bytecode", "d3d12_5_1")
STAGES = ("vs", "hs", "ds", "gs", "ps", "cs")

# The DXBC container carries an MD5 of its own contents at bytes 4..19, so two
# builds that differ in any metadata differ there too. Compare around it.
CHECKSUM_FIRST, CHECKSUM_LAST = 4, 19


def find_fxc():
    p = os.environ.get("FXC_PATH")
    if p and os.path.exists(p):
        return p
    pf = os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)")
    c = sorted(glob.glob(os.path.join(pf, "Windows Kits", "10", "bin", "*",
                                      "x64", "fxc.exe")))
    return c[-1] if c else None


def blob(path):
    """The numeric bytes of the shader array, ignoring comments and layout."""
    text = open(path, encoding="utf-8", errors="replace").read()
    # Everything after the array opens; the disassembly comment above it also
    # contains numbers, so anchor on the declaration.
    m = re.search(r"const BYTE\s+\w+\s*\[\s*\]\s*=\s*\{", text)
    if not m:
        return None
    tail = text[m.end():]
    end = tail.find("};")
    if end >= 0:
        tail = tail[:end]
    return [int(x) for x in re.findall(r"(?<![\w.])\d+(?![\w.])", tail)]


def stage_of(name):
    base = os.path.splitext(name)[0]          # foo.cs
    key = base.replace(".", "_")[-2:]
    return key if key in STAGES else None


def compile_one(fxc, src_dir, xesl, out_path):
    name = os.path.basename(xesl)
    stage = stage_of(name)
    if stage is None:
        return None
    ident = os.path.splitext(name)[0].replace(".", "_")
    args = [fxc, "/D", "SHADING_LANGUAGE_HLSL_XE=1", "/I", src_dir,
            "/Fh", out_path, "/T", "%s_5_1" % stage, "/Vn", ident,
            "/O3", "/Gfp", "/nologo", xesl]
    r = subprocess.run(args, capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    return r.returncode == 0, (r.stderr or "").strip(), ident


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sources", required=True,
                    help="directory holding src/xenia/gpu/shaders (and "
                         "src/xenia/ui/shaders, which they include)")
    ap.add_argument("--verify", action="store_true",
                    help="compare against the shipped headers, write nothing")
    ap.add_argument("--write", action="store_true",
                    help="replace the SDK's bytecode headers")
    ap.add_argument("--only", help="substring filter on the shader name")
    args = ap.parse_args()
    if not (args.verify or args.write):
        ap.error("choose --verify or --write")

    fxc = find_fxc()
    if not fxc:
        sys.exit("fxc.exe not found. Install the Windows 10 SDK or set FXC_PATH.")

    src_dir = os.path.join(args.sources, "src", "xenia", "gpu", "shaders")
    if not os.path.isdir(src_dir):
        sys.exit("no shader sources at %s" % src_dir)
    # The .xesl files include ../../ui/shaders/xesl.xesli, so that tree must sit
    # alongside them - this is not optional and fails with a bare "failed to
    # open source file" if it is missing.
    ui_dir = os.path.join(args.sources, "src", "xenia", "ui", "shaders")
    if not os.path.isdir(ui_dir):
        sys.exit("the shaders include ../../ui/shaders/xesl.xesli, but %s does "
                 "not exist - extract that tree too" % ui_dir)

    tmp = os.path.join(ROOT, "out", "shaderbuild")
    os.makedirs(tmp, exist_ok=True)

    same = differ = failed = skipped = 0
    diffs = []
    for xesl in sorted(glob.glob(os.path.join(src_dir, "*.xesl"))):
        name = os.path.basename(xesl)
        if args.only and args.only not in name:
            continue
        if stage_of(name) is None:
            continue
        ident = os.path.splitext(name)[0].replace(".", "_")
        shipped = os.path.join(BYTECODE, ident + ".h")
        if not os.path.exists(shipped):
            skipped += 1
            continue
        out = os.path.join(tmp, ident + ".h")
        ok, err, _ = compile_one(fxc, src_dir, xesl, out)
        if not ok:
            failed += 1
            print("  FAILED  %-52s %s" % (ident, err.splitlines()[-1][:60] if err else ""))
            continue
        a, b = blob(out), blob(shipped)
        if a is None or b is None:
            failed += 1
            print("  NOBLOB  %s" % ident)
            continue
        if len(a) != len(b):
            differ += 1
            diffs.append((ident, "length %d vs %d" % (len(a), len(b))))
            continue
        bad = [i for i in range(len(a)) if a[i] != b[i]
               and not (CHECKSUM_FIRST <= i <= CHECKSUM_LAST)]
        if bad:
            differ += 1
            diffs.append((ident, "%d bytes differ outside the checksum" % len(bad)))
        else:
            same += 1
            if args.write:
                os.replace(out, shipped)

    print("\nmatched %d, differed %d, failed %d, no shipped header %d"
          % (same, differ, failed, skipped))
    for ident, why in diffs[:20]:
        print("   %-52s %s" % (ident, why))
    if differ or failed:
        print("\nThe sources and the shipped bytecode do not agree. Do not "
              "regenerate shaders until they do.")
        return 1
    print("\nThe pipeline reproduces the shipped bytecode. Shader-touching "
          "Canary commits can be ported.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
