// GENERATED by tools/native_gpu/gen_gpu_cvars.py from the settings registry of the shipped rexgpu-xenos.dll (sha
// 476447cad811): before/after dumps of one run with FABLE2_CVARDUMP. Do not edit by hand - regenerate.
//
// rexgpu-xenos.dll is no longer loaded (2026-09-28). Everything it registered is registered here instead, with the same
// type, default, range, allowed values, lifecycle and description, so the settings file, the F10 menu, the startup
// tuning and the vendored backend's by-name readers (FLAGS_*_storage_ -> Plugin*/Refresh*) see exactly what they saw.
#include <charconv>
#include <cstdlib>
#include <deque>
#include <limits>
#include <string>
#include <string_view>

#include <rex/cvar.h>

namespace {
constexpr double kNoBound = std::numeric_limits<double>::quiet_NaN();
struct Def {
  const char* name;
  int type;        // rex::cvar::FlagType
  const char* category;
  int lifecycle;   // rex::cvar::Lifecycle
  const char* def;
  double min, max; // kNoBound = none
  const char* allowed;   // '|'-separated, empty = any
  const char* desc;
};
const Def kDefs[] = {
    {"anisotropic_override", 1, "GPU", 1, "3", -1.000000, 5.000000, "", "Forces anisotropic filtering for eligible textures. Higher values keep textures sharper at oblique angles, but increase texture sampling cost.  -1 = No override   0 = Disable anisotropic filtering   1 = Force 1x anisotropic filtering   2 = Force 2x anisotropic filtering   3 = Force 4x anisotropic filtering   4 = Force 8x anisotropic filtering   5 = Force 16x anisotropic filtering"},
    {"async_shader_compilation", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Compile shaders and create pipelines asynchronously in background threads. This reduces stutter but may cause brief visual artifacts while pipelines are being prepared."},
    {"clear_memory_page_state", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Refresh page-valid state from GPU-written memory at frame end. Disable for minor CPU overhead reduction, but may break memory coherency."},
    {"d3d12_bindless", 0, "GPU/D3D12", 2, "true", kNoBound, kNoBound, "", "Use bindless resources where available"},
    {"d3d12_dxbc_disasm", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "Dump DXBC disassembly"},
    {"d3d12_dxbc_disasm_dxilconv", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "Dump DXIL conversion disassembly"},
    {"d3d12_pipeline_creation_threads", 1, "GPU/D3D12", 2, "-1", -1.000000, 32.000000, "", "Number of pipeline creation threads (-1 for auto)"},
    {"d3d12_readback_memexport", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "Read data written by memory export in shaders on the CPU"},
    {"d3d12_readback_resolve", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "Read render-to-texture results on the CPU"},
    {"d3d12_submit_on_primary_buffer_end", 0, "GPU/D3D12", 1, "true", kNoBound, kNoBound, "", "Submit command list when PM4 primary buffer ends"},
    {"d3d12_tessellation_wireframe", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "Render tessellation as wireframe"},
    {"d3d12_tiled_shared_memory", 0, "GPU/D3D12", 2, "true", kNoBound, kNoBound, "", "Use tiled shared memory on D3D12"},
    {"depth_float24_convert_in_pixel_shader", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Convert float24 depth in pixel shader"},
    {"depth_float24_round", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Round float24 depth values"},
    {"depth_transfer_not_equal_test", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Use not-equal test for depth transfer"},
    {"diag_alpha_test_off", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "DIAGNOSTIC: never reject a pixel on the alpha test. Makes alpha-tested geometry render solid - the point is to find out whether the alpha test is what removes geometry that is otherwise submitted."},
    {"diag_cull_none", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "DIAGNOSTIC: force the rasterizer cull mode to NONE, ignoring the guest's face culling. Renders back faces that should be hidden - the point is to find out whether geometry is being culled away."},
    {"diag_depth_always", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "DIAGNOSTIC: force the depth comparison to ALWAYS, so nothing is rejected by the depth test. Breaks occlusion - the point is to find out whether geometry is being depth-rejected."},
    {"diag_vs_const_nan_fix", 1, "GPU", 1, "0", kNoBound, kNoBound, "", "DIAGNOSTIC: substitute for NaN in vertex shader float constants. 1 replaces NaN with 0; 2 replaces it with the matching row of an identity matrix (assuming 4-register-aligned matrices). The census proved NaN reaches these constants; this establishes whether that NaN CAUSES the flat-blue scene or merely accompanies it."},
    {"direct_host_resolve", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Resolve from host render targets directly to shared memory when possible"},
    {"draw_census", 1, "GPU", 1, "0", kNoBound, kNoBound, "", "Log a summary of draws issued and draws dropped (and why) every N seconds. 0 disables. Diagnostic: four of the five ways a draw can be dropped return silently, so nothing else distinguishes 'issued but invisible' from 'never issued'."},
    {"draw_resolution_scale_x", 1, "GPU", 2, "1", 1.000000, 8.000000, "", "Draw resolution scale X (1 = no scaling)"},
    {"draw_resolution_scale_y", 1, "GPU", 2, "1", 1.000000, 8.000000, "", "Draw resolution scale Y (1 = no scaling)"},
    {"draw_resolution_scaled_texture_offsets", 0, "GPU/Shader", 1, "true", kNoBound, kNoBound, "", "Scale texture offsets with draw resolution"},
    {"dump_shaders", 6, "GPU", 1, "", kNoBound, kNoBound, "", "Path to dump shaders to"},
    {"dxbc_source_map", 0, "GPU/Shader", 1, "false", kNoBound, kNoBound, "", "Generate source maps for DXBC"},
    {"dxbc_switch", 0, "GPU/Shader", 1, "true", kNoBound, kNoBound, "", "Use switch statements in DXBC"},
    {"execute_unclipped_draw_vs_on_cpu", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Execute unclipped draw vertex shader on CPU"},
    {"execute_unclipped_draw_vs_on_cpu_for_psi_render_backend", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Execute unclipped draw VS on CPU for PSI render backend"},
    {"execute_unclipped_draw_vs_on_cpu_with_scissor", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Execute unclipped draw VS on CPU with scissor"},
    {"fable2_2d_census", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "Diagnostic: log the first N distinct vertex shaders with their 2D/3D classification"},
    {"fable2_menu_letterbox_gap_ms", 1, "GPU/D3D12", 1, "150", kNoBound, kNoBound, "", "Fable II ultrawide: a world scene whose camera has been stale this many ms is a full-screen pause/Up menu; the app fades to black over its open/close to hide the game's aspect blip (0 = no fade; the app reads this)"},
    {"fable2_uw_2d_k", 5, "GPU/D3D12", 1, "0.000000", kNoBound, kNoBound, "", "Fable II ultrawide: scale the 2D HUD's pixel-to-clip constant (c8) x by this factor (16:9 / display aspect) so the HUD keeps its proportions; 0 = off"},
    {"force_convert_line_loops_to_strips", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Force convert line loops to strips"},
    {"force_convert_quad_lists_to_triangle_lists", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Force convert quad lists to triangle lists"},
    {"force_convert_triangle_fans_to_lists", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Force convert triangle fans to lists"},
    {"force_depth_clamp", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Use host depth clamping instead of near and far plane clipping when guest clipping is enabled. X/Y/W clipping is unaffected. On Vulkan, this requires depthClamp support."},
    {"gamma_render_target_as_unorm16", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Use R16G16B16A16_UNORM for gamma render targets (more accurate than sRGB)"},
    {"gpu_3d_to_2d_texture", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Sample problematic 3D textures through 2D-compatible wrappers"},
    {"gpu_allow_invalid_fetch_constants", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Allow invalid fetch constants"},
    {"gpu_dcl_census", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "Count the Direct3D 12 commands replayed per kind (costs frames; diagnostic)"},
    {"gpu_debug_markers", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Insert debug markers into GPU command streams for tools like PIX and RenderDoc. Automatically enabled when RenderDoc is detected."},
    {"gpu_draw_dump_file", 6, "GPU/D3D12", 1, "", kNoBound, kNoBound, "", "Diagnostic: the file gpu_draw_dump_frames writes its per-draw lines to"},
    {"gpu_draw_dump_hashes", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "Diagnostic: 1 = the draw dump also hashes each draw's vertex buffers and used constants (costs ~30 fps at 3x)"},
    {"ngpu_exp_atlas_readback", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "EXPERIMENT ONLY: read the tree-impostor atlas bytes back from the GPU into ngpu_exp_atlas_readback_file, one summary line per atlas per frame: bit 1 = the scaled range right after each atlas resolve (what the resolve wrote), bit 2 = the texture right before each billboard draw samples it (what the draw sees); bit 4 = the billboard vertex shader lookup textures (tf16/tf17), whole, right before the draw, with the guest bytes hash; bit 8 = the billboard draws' float constants, CPU register values and the GPU-side constant buffer bytes side by side; bit 16 = with bit 2, mips 1-3 of the atlas texture as well (the same window); bit 32 = the billboard draws' SYSTEM constants (texture sign/gamma flags) CPU and GPU side, with the pipeline modification keys and the raw t0 fetch constant; bit 64 = the sampling probe (a compute dispatch that samples the atlas through the draw's own bindless descriptor index at one texel and records the RGBA it gets - the fetch's OUTPUT; bindless mode only); 127 = all"},
    {"ngpu_exp_atlas_readback_amask", 1, "GPU/D3D12", 1, "-1", kNoBound, kNoBound, "", "EXPERIMENT ONLY: bit n arms the A side (after the resolve) on impostor species slot n (atlas 0x12704000 + n * 0x2B000); -1 = all"},
    {"ngpu_exp_runlag", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "EXPERIMENT ONLY: run-ahead instruments at the impostor draws: 1 = ring lag (game write pointer ahead of the CP) per draw and swap; 2 = hash the guest vertex ranges and lookup-table pages of the draw at record time and again at the swap; 4 = TREATMENT: invalidate and re-upload the vertex ranges before the draw on the species in ngpu_exp_runlag_mask"},
    {"ngpu_exp_ps_texel_zero", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "EXPERIMENT ONLY (picture oracle): 1 = force c31.x to 0 for the lit impostor pixel shader 4B1D, so every card renders its vertex-stage o3 term alone (alpha untouched); species in ngpu_exp_ps_texel_zero_mask only"},
    {"ngpu_exp_ps_texel_zero_mask", 1, "GPU/D3D12", 1, "-1", kNoBound, kNoBound, "", "EXPERIMENT ONLY: bit n arms the o3-only oracle on impostor species slot n; -1 = all"},
    {"ngpu_kick_pacing", 1, "GPU/D3D12", 1, "1", kNoBound, kNoBound, "", "Kick pacing: the game's kick to the graphics thread waits while this many flattened batches (or more) are still queued for the recording thread, bounded to 100 ms per kick; 0 = off. In testing it removed the one-frame violet tree-impostor flashes at high internal resolution (the cause is not identified - see the release notes). ngpu_exp_kick_throttle overrides it when set."},
    {"ngpu_kick_pacing_min_scale", 1, "GPU/D3D12", 1, "1", kNoBound, kNoBound, "", "Kick pacing applies only at internal resolution scale >= this value. 1 (the default) = every scale: at 1x the pacing measured no cost (59 against 60 fps presented, fewer hitches). Set 3 to pace only at the scale where the flash was seen."},
    {"ngpu_exp_kick_throttle", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "EXPERIMENT ONLY: hold the game at its kick until fewer than N flattened batches wait for the recorder (bounded 100 ms per kick); 0 = off"},
    {"ngpu_exp_runlag_mask", 1, "GPU/D3D12", 1, "-1", kNoBound, kNoBound, "", "EXPERIMENT ONLY: bit n arms runlag bit 4 on impostor species slot n; -1 = all"},
    {"ngpu_exp_atlas_readback_probe_lod", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "EXPERIMENT ONLY: the mip level the sampling probe reads (0-3); the far impostor cards sample mips 2-3"},
    {"ngpu_exp_atlas_readback_probe_mode", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "EXPERIMENT ONLY: sampling probe shader: 0 = sample the atlas through the draw's descriptor index (the instrument); 1 = the same dispatch, barriers and copy with a shader that never touches the texture (the control for the probe as a treatment); 2 = compile and create the probe pipeline at the first billboard draw but never dispatch (the hitch-only control); 3 = compile and create the pipeline at the third swap (the menu, before any world load) and then sample as mode 0; 4 = the pipeline switch only; 5 = the barriers only; 6 = an early SubmitBarriers only; 7 = the bare dispatch (no barrier, no copy)"},
    {"ngpu_exp_atlas_readback_pmask", 1, "GPU/D3D12", 1, "-1", kNoBound, kNoBound, "", "EXPERIMENT ONLY: bit n arms the sampling probe (bit 64) on impostor species slot n; -1 = all - a within-leg control for the probe as a treatment"},
    {"ngpu_exp_atlas_readback_tmask", 1, "GPU/D3D12", 1, "-1", kNoBound, kNoBound, "", "EXPERIMENT ONLY: bit n arms the T side (before the billboard draw) on impostor species slot n; -1 = all - a within-frame control: armed species against unarmed ones in one leg"},
    {"ngpu_exp_atlas_readback_file", 6, "GPU/D3D12", 1, "", kNoBound, kNoBound, "", "EXPERIMENT ONLY: the file ngpu_exp_atlas_readback writes to (empty = instrument off)"},
    {"ngpu_exp_atlas_sentinel", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "EXPERIMENT ONLY: 1 = before every small scaled resolve (the tree impostor atlases) add COPY_DEST/UAV transitions around nothing (the barrier-only control); 2 = the same transitions around a fill of the destination range with k_1_5_5_5 green, so a texture that reads the range before the resolve writes land shows green instead of stale content (the canopy-flash sentinel test); 3 = the same fill AFTER the resolve (positive control: every canopy must show the fill colour); 4 = fill the EDRAM-buffer tile span BEFORE the host render targets are dumped into it (source side); 5 = the same after the dump (its positive control); 6 = BLUE (0x801F) into the UNSCALED shared-memory copy of the range after the resolve (does the flash read the unscaled copy?); 7 = only TouchRange those pages (the hoist bookkeeping), no fill; 8 = only the shared-memory buffer transition to COPY_DEST after the resolve, no touch, no fill; 9 = an explicit UAV barrier on the scaled buffer before every atlas load's SRV transition"},
    {"ngpu_exp_cbuf_early", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "EXPERIMENT ONLY: reclaim constant-buffer pages this many frames early (a deliberate hazard to test whether the per-draw constants are the medium of the canopy flash)"},
    {"ngpu_exp_upload_early", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "EXPERIMENT ONLY: reclaim shared-memory upload pages this many submissions early (a deliberate hazard)"},
    {"ngpu_exp_scratch_nobarrier", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "EXPERIMENT ONLY: drop the scratch buffer transition between consecutive texture loads (a deliberate hazard)"},
    {"gpu_draw_dump_filter", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "Diagnostic: 1 = the draw dump keeps only draws sampling a GPU-written or a wide 8888 texture (impostors)"},
    {"gpu_draw_dump_frames", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "Diagnostic: write one line per draw for this many guest frames to gpu_draw_dump_file, then reset to 0 (the app's pad command dump:N sets it)"},
    {"gpu_frame_depth_draws", 1, "GPU", 1, "0", kNoBound, kNoBound, "", "Depth-tested draws in the last presented guest frame (stat)"},
    {"gpu_frame_draws", 1, "GPU", 1, "0", kNoBound, kNoBound, "", "Draws in the last presented guest frame (stat)"},
    {"gpu_offload_to_native", 0, "GPU/D3D12", 2, "false", kNoBound, kNoBound, "", "Hand all GPU work to the in-app native renderer (the plugin only parses PM4 and feeds the bridge); needs the native backend enabled"},
    {"guest_fps_x10", 1, "GPU", 1, "0", kNoBound, kNoBound, "", "Guest frames per second x10 over the last second, from the game's swaps (the game's own rate, not the host present rate)"},
    {"half_pixel_offset", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Enable half pixel offset"},
    {"mrt_edram_used_range_clamp_to_min", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Clamp MRT EDRAM used range to minimum"},
    {"native_2x_msaa", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Enable native 2x MSAA"},
    {"native_stencil_value_output", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Enable native stencil value output"},
    {"native_stencil_value_output_d3d12_intel", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "Native stencil value output for Intel D3D12"},
    {"ng2_fov_k", 5, "GPU", 1, "1.000000", kNoBound, kNoBound, "", "NG2 horizontal-FOV (Hor+) scale. Multiplies column 0 of the c21-c24 world-view-projection on perspective draws, which widens (k<1) or narrows (k>1) horizontal FOV while leaving vertical FOV, depth, and 2D/ortho draws (menus, videos, HUD) untouched. 1.0 = off. Hot-reloadable: set live from the game's FOV slider via rex::cvar::SetFlagByName(\"ng2_fov_k\", ...)."},
    {"ng2_uw_mode", 1, "GPU", 1, "0", kNoBound, kNoBound, "", "NG2 ultrawide present mode, set by the GPU scene detector and read by the presenter across the DLL boundary: 0 = off (user's aspect setting), 1 = gameplay (fill + FOV widen), 2 = menu/video (pillarbox 16:9). Internal; do not set by hand."},
    {"non_seamless_cube_map", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Use non-seamless cube map sampling"},
    {"occlusion_query_enable", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Enable host occlusion query handling"},
    {"pre_mask_resolve_l2_block", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Pre-mask scaled resolve L2 blocks to the write range before iterating"},
    {"primitive_processor_cache_min_indices", 1, "GPU", 1, "0", 0.000000, 1000000.000000, "", "Minimum indices for primitive processor cache"},
    {"query_occlusion_fake_sample_count", 1, "GPU", 1, "1000", 1.000000, 100000.000000, "", "Fake sample count for occlusion queries"},
    {"readback_await_before_texture_upload", 0, "GPU/D3D12", 1, "true", kNoBound, kNoBound, "", "A texture upload that reads guest memory still waiting for a resolve readback from an EARLIER submission waits for that submission (only) and lands the copy first, so it never uploads stale bytes (the white/magenta streaming flash). Replaces the resolve-time drain (readback_resolve_drain_large_kb), which waited for the whole GPU queue at every large resolve: 28-38 guest fps in town."},
    {"readback_fast_path_gpu_written", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "The impostor readback fast path asks whether the pages it is about to skip a wait for are already correct in the GPU buffer. TRUE asks GPU-written, FALSE asks merely valid, which is what shipped in v0.2.12. The two are the same question only while clear_memory_page_state is off. MEASURED, two alternating rounds on a quiet machine: the rounds DISAGREED in direction (46.0/45.7 then 46.9/47.1 fps) and the waits it exists to avoid did not move (3263/3239 then 3324/3329 per 5 s), so it makes no difference to Fable in the scene sampled. Defaulted FALSE, which is what v0.2.12 shipped, because a change with no measurable effect whose original justification was disproved should not ride along inside a hotfix. The code stays, so a title that does exercise this path can turn it on"},
    {"readback_land_before_texture_upload", 0, "GPU/D3D12", 1, "true", kNoBound, kNoBound, "", "Before a texture loads from resident memory, land any completed deferred resolve copy into its range (fixes the black distant-impostor flash on reload frames)"},
    {"readback_memexport", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Enable CPU readback of shader memexport writes for guest memory coherency (can reduce correctness issues, but may add GPU/CPU sync cost)"},
    {"readback_memexport_fast", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Use fast double-buffered memexport readback when possible, with automatic fallback to full synchronous readback"},
    {"readback_resolve", 6, "GPU", 1, "none", kNoBound, kNoBound, "none|fast|some|full", "Controls CPU readback of render-to-texture resolve results.  none: Disable readback (default)  fast: Read previous frame (delayed, copy every frame)  some: Read previous frame (delayed, copy on cache miss)  full: Immediate sync readback (accurate but stalls)"},
    {"readback_resolve_drain_large_kb", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "Wait for the GPU and land the copy synchronously for every resolve of at least this many KB, so a large render-to-texture (sky, water, a distant impostor) is valid in guest memory before any texture reads it - the white/magenta streaming flash was such a target uploaded while its readback was still in flight. Small resolves stay async. 0 = never (costs frame rate in proportion to how many big resolves a scene streams)."},
    {"readback_resolve_drain_max_kb", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "Experiment: with readback_resolve_drain_large_kb, drain only resolves of at most this many KB (0 = no upper bound)"},
    {"readback_resolve_drain_small_kb", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "With readback_resolve=some, wait for the GPU after every resolve of at most this many KB (0 = never)"},
    {"readback_resolve_half_pixel_offset", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "When draw resolution scaling is active, sample from the center of each scaled block during resolve readback downscale"},
    {"readback_resolve_keep_superseded", 0, "GPU/D3D12", 1, "true", kNoBound, kNoBound, "", "Keep a deferred resolve copy pending when the same target is resolved again before it landed (it lands when its submission completes, from the same buffer), instead of dropping it and leaving the CPU copy stale - the stale bytes were uploaded over the render on the next invalidation: the white/violet impostor flash"},
    {"readback_resolve_mirror_unscaled", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "At a draw resolution scale above 1, also copy the 1x downscale of every resolve into the unscaled shared memory buffer on the GPU (the resolve itself only writes the scaled buffer), so a texture loaded from the unscaled copy of a resolved range shows the render and not the stale fill the CPU last uploaded there - the white/magenta impostor flash. One GPU buffer copy per resolve, no wait (0.2.11)"},
    {"readback_resolve_on_demand", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "Watch deferred resolve targets and land their copy the moment the CPU touches them"},
    {"readback_resolve_rebind_small_kb", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "Experiment: re-bind the render targets after every deferred resolve of at most this many KB (0 = never)"},
    {"readback_resolve_split_before_load", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "End the GPU submission (a full sync, no wait) right before a texture is loaded from memory the GPU resolved in the still-open submission - the streaming flash's hazard - instead of after every resolve (readback_resolve_submit_small_kb): hundreds of splits a second instead of thousands (0.2.11)"},
    {"readback_resolve_submit_small_kb", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "End the submission (no wait) after every deferred resolve of at most this many KB (0 = never); a command-list boundary is a full GPU barrier and stops the white impostor flashes. Was 64: the larger resolves (sky, water, the distant impostors) flashed too, and the 0.2.10 drain that cured them was this boundary plus a wait for the whole queue; the boundary alone is the cure without the wait (0.2.11)"},
    {"readback_resolve_sync_budget", 1, "GPU/D3D12", 1, "8", kNoBound, kNoBound, "", "Resolve readbacks per frame that may wait for the GPU before copying; the rest are copied when their submission completes (0 = never wait)"},
    {"readback_resolve_uav_barrier", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "Experiment: explicit UAV barriers on the shared memory and EDRAM buffers after every resolve"},
    {"scaled_resolve_uav_barrier", 0, "GPU/D3D12", 1, "true", kNoBound, kNoBound, "", "UAV barrier between consecutive resolves into the same scaled-resolution buffer (the pending-writes flag was never consumed: a write-after-write race between resolves, seen as the one-frame violet/magenta tree-canopy flash at 3x). false = the old behaviour, for A/B only"},
    {"readback_resolve_wait_only_kb", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "Experiment: at every resolve of at least this many KB wait for the GPU queue as the drain does, but keep the copy on the asynchronous path (0 = off) - splits the drain's cure into its wait and its immediate copy"},
    {"render_target_path_d3d12", 6, "GPU/D3D12", 0, "", kNoBound, kNoBound, "", "D3D12 render target implementation path"},
    {"render_target_path_vulkan", 6, "GPU/Vulkan", 0, "", kNoBound, kNoBound, "", "Vulkan render target implementation path"},
    {"resolution_scale", 1, "GPU", 2, "1", 1.000000, 8.000000, "", "Draw resolution scale for both X and Y axes (same as setting draw_resolution_scale_x and draw_resolution_scale_y)"},
    {"resolve_resolution_scale_fill_half_pixel_offset", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Fill half pixel offset during resolution scale resolve"},
    {"reveal_hold", 0, "GPU/D3D12", 1, "true", kNoBound, kNoBound, "", "After a load, show the stage only once it is complete (hides the partially drawn first frames)"},
    {"reveal_hold_frames", 1, "GPU/D3D12", 1, "6", kNoBound, kNoBound, "", "Consecutive complete frames that end the post-load reveal hold"},
    {"reveal_hold_max_ms", 1, "GPU/D3D12", 1, "2500", kNoBound, kNoBound, "", "The post-load reveal hold never lasts longer than this (ms)"},
    {"shared_memory_upload_churn", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "Diagnostic: hash a sample of every re-uploaded range and report how much of the upload volume is bytes that did not change since they were last uploaded. With clear_memory_page_state on a title re-reads its CPU-sourced working set every frame; this says whether that work is necessary or waste"},
    {"shared_memory_upload_reach", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "Diagnostic: report how often a single contiguous dirty upload run reaches the 256 KB threshold that hands the copy to the worker pool, and the largest one seen. Answers whether a title exercises the pool at all - unreachable and merely unobserved are different claims and only this tells them apart"},
    {"shared_memory_upload_skip_unchanged", 0, "GPU/D3D12", 1, "false", kNoBound, kNoBound, "", "Skip the upload of any 4 KB page whose bytes are identical to the ones last uploaded for it - the GPU buffer already holds them. Under clear_memory_page_state 71% of the upload volume is such bytes. Safe because a GPU write to a page evicts its recorded hash, so the skip can never leave a resolve output where CPU data belongs"},
    {"shared_memory_upload_spin_ns", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "Diagnostic: busy-spin this many nanoseconds per upload range, touching nothing. Pure latency with no memory access - if this alone suppresses the NG2 freeze, the freeze is a timing race and no volume story explains it"},
    {"shared_memory_upload_threads", 1, "GPU/D3D12", 1, "3", kNoBound, kNoBound, "", "Helper threads for the guest-memory to upload-buffer copies (0 = copy inline on the command thread; the market uploads ~18 MB a frame)"},
    {"shared_memory_upload_touch_bytes", 1, "GPU/D3D12", 1, "0", kNoBound, kNoBound, "", "Diagnostic: read this many bytes from the start of each page of each upload range into a volatile sink, hashing nothing (0 = off). One probe with one parameter, so a difference between legs cannot be a difference between probes. 1 byte holds residency constant at near-zero bandwidth; 4096 is the same traffic as the churn probe with none of its compute. If suppression tracks the byte count, the mechanism is memory traffic; if only hashing suppresses, it is the work and not the read"},
    {"snorm16_render_target_full_range", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Use full range for SNORM16 render targets"},
    {"spirv_disable_rounding_mode_rte", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Disable RoundingModeRTE capability in SPIR-V shaders. Enable this to allow shader debugging in RenderDoc, which doesn't support this capability."},
    {"store_shaders", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Store shaders persistently and load them when loading games to avoid runtime spikes and freezes when playing the game not for the first time."},
    {"swap_post_effect", 6, "GPU", 2, "none", kNoBound, kNoBound, "none|fxaa|fxaa_extreme", "Swap post effect: none, fxaa, fxaa_extreme"},
    {"texture_cache_memory_limit_hard", 1, "GPU", 2, "768", 128.000000, 8192.000000, "", "Hard texture cache memory limit (MB)"},
    {"texture_cache_memory_limit_render_to_texture", 1, "GPU", 2, "24", 1.000000, 256.000000, "", "Texture cache memory limit for render-to-texture (MB)"},
    {"texture_cache_memory_limit_soft", 1, "GPU", 2, "384", 64.000000, 4096.000000, "", "Soft texture cache memory limit (MB)"},
    {"texture_cache_memory_limit_soft_lifetime", 1, "GPU", 1, "30", 1.000000, 3600.000000, "", "Soft texture cache memory limit lifetime (seconds)"},
    {"texture_dump", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Dump every unique guest texture to texture_dump_path for offline decoding and upscaling. Off by default."},
    {"texture_dump_path", 6, "GPU", 1, "", kNoBound, kNoBound, "", "Where texture_dump writes. Empty = disabled."},
    {"texture_pack_chapter", 1, "GPU", 1, "0", kNoBound, kNoBound, "", "Chapter currently loading, for per-stage pack warming"},
    {"texture_pack_original", 1, "GPU", 1, "0", kNoBound, kNoBound, "", "Read-only: textures loaded from the game this run"},
    {"texture_pack_path", 6, "GPU", 1, "", kNoBound, kNoBound, "", "Folder of replacement textures to load instead of the game's own. Empty = disabled."},
    {"texture_pack_replaced", 1, "GPU", 1, "0", kNoBound, kNoBound, "", "Read-only: textures loaded from the pack this run"},
    {"texture_pack_resolve_at_load", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Match pack textures by the bytes in memory at LOAD, not at creation. Fixes streamed textures (e.g. NG2 chapter 10) whose bytes are not written yet at creation. Off by default."},
    {"texture_pack_upload_budget_mb", 1, "GPU", 1, "0", kNoBound, kNoBound, "", "Pack texture bytes uploaded per frame before the rest wait for later frames (0 = no limit). Off: measured a loss at 24 MB - the copies were never the hitch (Fable II, 2026-09-13)"},
    {"texture_warm_done", 1, "GPU", 1, "0", kNoBound, kNoBound, "", "Files warmed so far in the current stage"},
    {"texture_warm_total", 1, "GPU", 1, "0", kNoBound, kNoBound, "", "Files in the stage being warmed (0 = not warming)"},
    {"use_fuzzy_alpha_epsilon", 0, "GPU", 1, "false", kNoBound, kNoBound, "", "Use approximate compare for alpha test values to prevent flickering on NVIDIA graphics cards"},
    {"vsync", 0, "GPU", 1, "true", kNoBound, kNoBound, "", "Enable vertical sync"},
    {"vulkan_async_skip_incomplete_frames", 0, "GPU/Vulkan", 1, "true", kNoBound, kNoBound, "", "When async shader compilation is enabled, skip presenting frames that used placeholder pipelines to avoid visible flashing"},
    {"vulkan_dynamic_rendering", 0, "GPU/Vulkan", 1, "true", kNoBound, kNoBound, "", "Use VK_KHR_dynamic_rendering for Vulkan GPU emulation when supported by the device (falls back to render passes otherwise)"},
    {"vulkan_force_convert_quad_lists_to_triangle_lists", 0, "GPU/Vulkan", 0, "false", kNoBound, kNoBound, "", "Force Vulkan quad list conversion to triangle lists in primitive processing, even when geometry shaders are available"},
    {"vulkan_force_expand_point_sprites_in_vs", 0, "GPU/Vulkan", 0, "false", kNoBound, kNoBound, "", "Force Vulkan point sprite expansion in the vertex shader, even when geometry shaders are available"},
    {"vulkan_force_expand_rectangle_lists_in_vs", 0, "GPU/Vulkan", 0, "false", kNoBound, kNoBound, "", "Force Vulkan rectangle list expansion in the vertex shader, even when geometry shaders are available"},
    {"vulkan_pipeline_creation_threads", 1, "GPU/Vulkan", 2, "-1", -1.000000, 32.000000, "", "Number of pipeline creation threads for Vulkan async pipeline creation (-1 for auto)"},
    {"vulkan_readback_memexport", 0, "GPU/Vulkan", 1, "false", kNoBound, kNoBound, "", "Read data written by memory export in shaders on the CPU"},
    {"vulkan_readback_resolve", 0, "GPU/Vulkan", 1, "false", kNoBound, kNoBound, "", "Read render-to-texture results on the CPU"},
    {"vulkan_sparse_shared_memory", 0, "GPU/Vulkan", 2, "true", kNoBound, kNoBound, "", "Use sparse shared memory on Vulkan"},
    {"vulkan_submit_on_primary_buffer_end", 0, "GPU/Vulkan", 1, "true", kNoBound, kNoBound, "", "Submit command buffer when PM4 primary buffer ends"},
    {"vulkan_tessellation_wireframe", 0, "GPU/Vulkan", 1, "false", kNoBound, kNoBound, "", "Render tessellation as wireframe"},
};

std::string NormalizeBool(std::string_view v) {
  std::string s(v);
  for (char& c : s) c = char(std::tolower(static_cast<unsigned char>(c)));
  return (s == "true" || s == "1" || s == "yes" || s == "on") ? "true" : "false";
}

struct Registrations {
  std::deque<std::string> values;   // one live value per entry (stable addresses)
  Registrations() {
    for (const Def& d : kDefs) {
      values.emplace_back(d.def);
      std::string* value = &values.back();
      const auto type = rex::cvar::FlagType(d.type);
      rex::cvar::FlagEntry e;
      e.name = d.name;
      e.type = type;
      e.category = d.category;
      e.description = d.desc;
      e.lifecycle = rex::cvar::Lifecycle(d.lifecycle);
      e.default_value = d.def;
      if (d.min == d.min) e.constraints.min = d.min;
      if (d.max == d.max) e.constraints.max = d.max;
      for (std::string_view rest = d.allowed; !rest.empty();) {
        const size_t bar = rest.find('|');
        e.constraints.allowed_values.emplace_back(rest.substr(0, bar));
        rest = bar == std::string_view::npos ? std::string_view() : rest.substr(bar + 1);
      }
      e.setter = [value, type](std::string_view v) {
        switch (type) {
          case rex::cvar::FlagType::Boolean: *value = NormalizeBool(v); return true;
          case rex::cvar::FlagType::Int32:
          case rex::cvar::FlagType::Int64: {
            long long x = 0;
            auto [p, ec] = std::from_chars(v.data(), v.data() + v.size(), x);
            if (ec != std::errc()) return false;
            *value = std::to_string(x);
            return true;
          }
          case rex::cvar::FlagType::Uint32:
          case rex::cvar::FlagType::Uint64: {
            unsigned long long x = 0;
            auto [p, ec] = std::from_chars(v.data(), v.data() + v.size(), x);
            if (ec != std::errc()) return false;
            *value = std::to_string(x);
            return true;
          }
          case rex::cvar::FlagType::Double: {
            std::string s(v);
            char* end = nullptr;
            std::strtod(s.c_str(), &end);
            if (end == s.c_str()) return false;
            *value = s;
            return true;
          }
          default: *value = std::string(v); return true;
        }
      };
      e.getter = [value] { return *value; };
      e.command_callback = [](std::string_view) {};
      rex::cvar::RegisterFlag(std::move(e));
    }
  }
};
Registrations g_registrations;
}  // namespace
