// GENERATED by ng2recomp/tools/native_gpu/gen_trace_hooks.py. The native-GPU
// call-census tracer: every Direct3D library entry point and device state
// setter has a mid-asm hook at its first instruction that counts the call and
// keeps the first argument samples; a census goes to the log every 10 s
// ([ngpu] lines). Enabled by the ngpu_trace cvar (default off: the hooks
// cost one load and one compare each when off).
#include "fable2_p2_census.h"
#include "native_gpu_dump.h"
#include "native_gpu_present.h"
#include <rex/cvar.h>
#include <rex/logging.h>
#include <rex/ppc/context.h>

#include <atomic>
#include <chrono>
#include <cstdint>
#include <mutex>

REXCVAR_DEFINE_BOOL(ngpu_trace, false, "GPU", "Log a call census of the Direct3D library entry points every 10 s");

namespace {
constexpr int kHooks = 304;
constexpr int kSamples = 4;
struct Entry { uint32_t addr; const char* label; };
const Entry kEntries[kHooks] = {
  {0x82188750, "SetRenderState_FILLMODE"},
  {0x82188770, "SetRenderState_MAXTESSELLATIONLEVEL"},
  {0x82188798, "SetRenderState_POINTSIZE_MAX"},
  {0x821887D8, "SetRenderState_STENCILFAIL"},
  {0x82188800, "SetRenderState_STENCILZFAIL"},
  {0x82188828, "SetRenderState_WRAP1"},
  {0x82188850, "SetRenderState_WRAP11"},
  {0x82188878, "SetRenderState_WRAP13"},
  {0x821888A0, "SetRenderState_WRAP15"},
  {0x821888C0, "SetRenderState_WRAP3"},
  {0x821888E8, "SetRenderState_WRAP5"},
  {0x82188910, "SetRenderState_WRAP7"},
  {0x82188930, "SetRenderState_WRAP9"},
  {0x82193008, "ring"},
  {0x82196628, "ring"},
  {0x82196750, "ring"},
  {0x8219CCC0, "SetRenderState_POINTSIZE_MIN"},
  {0x8219CD68, "ring"},
  {0x821A1700, "ring"},
  {0x821A8B88, "SetRenderState_BLENDFACTOR"},
  {0x821A8C18, "SetRenderState_SLOPESCALEDEPTHBIAS"},
  {0x821B1330, "SetRenderState_ALPHAFUNC"},
  {0x821B1350, "SetRenderState_STENCILWRITEMASK"},
  {0x821B6C60, "dirty bits=19 writes=0,24,13524"},
  {0x821B9A08, "ring"},
  {0x821BFDF0, "SetRenderState_ZFUNC"},
  {0x821C19F0, "ring"},
  {0x821C6478, "ring"},
  {0x821C91C8, "SetRenderState_COLORWRITEENABLE"},
  {0x821CD310, "ring"},
  {0x821DC158, "SetRenderState_SRCBLEND"},
  {0x821DCAA0, "SetRenderState_ALPHABLENDENABLE"},
  {0x821E0BF8, "SetRenderState_HISTENCILFUNC"},
  {0x821E2C08, "ring"},
  {0x821E5290, "SetSamplerState_MAXANISOTROPY"},
  {0x821E56F8, "SetRenderState_STENCILENABLE"},
  {0x821EC798, "SetSamplerState_MIPMAPLODBIAS"},
  {0x821EFAC0, "ring"},
  {0x821F0490, "SetRenderState_DESTBLEND"},
  {0x821F0E00, "ring"},
  {0x821F6270, "ring"},
  {0x821F6300, "ring"},
  {0x821F9918, "ring"},
  {0x821F9D00, "dirty bits=21,22,23,24,25,26 writes=12672"},
  {0x82202D10, "SetSamplerState_ADDRESSU"},
  {0x82205F68, "ring"},
  {0x82206888, "ring"},
  {0x82207AF8, "ring"},
  {0x82208020, "SetRenderState_ALPHATOMASKOFFSETS"},
  {0x82208BB0, "dirty bits=17,20 writes=0,8,32,12692,13524"},
  {0x8220A490, "SetRenderState_ALPHATOMASKENABLE"},
  {0x8220B470, "SetRenderState_CULLMODE"},
  {0x8220BD40, "ring"},
  {0x82213AD8, "ring"},
  {0x82215488, "SetRenderState_ALPHATESTENABLE"},
  {0x822154B0, "ring"},
  {0x82217DB8, "ring"},
  {0x822192E8, "ring"},
  {0x822194B8, "ring"},
  {0x8221AE18, "ring"},
  {0x8221B010, "ring"},
  {0x8221C3E8, "ring"},
  {0x8221C898, "ring"},
  {0x8221D190, "SetRenderState_HIZENABLE"},
  {0x8221D1B0, "ring"},
  {0x8221DFC0, "ring"},
  {0x8221E410, "SetRenderState_HIGHPRECISIONBLENDENABLE"},
  {0x82221740, "ring"},
  {0x82221858, "ring"},
  {0x82221B90, "ring"},
  {0x822224A8, "dirty bits=19 writes=11820"},
  {0x82223B50, "ring"},
  {0x82225E08, "SetRenderState_ALPHAREF"},
  {0x8222B8F0, "ring"},
  {0x8222BFA0, "ring"},
  {0x8222C568, "SetSamplerState_ADDRESSV"},
  {0x8222C818, "SetSamplerState_MIPFILTER"},
  {0x82232510, "dirty bits=19 writes=0,32,10942,12696,13524"},
  {0x822373F0, "SetSamplerState_ADDRESSW"},
  {0x82238128, "SetSamplerState_MINFILTER"},
  {0x822383A0, "SetSamplerState_MAGFILTER"},
  {0x822398D0, "SetSamplerState_TRILINEARTHRESHOLD"},
  {0x82239910, "SetRenderState_STENCILREF"},
  {0x8223B130, "dirty bits= writes=0,4,8"},
  {0x82242668, "ring"},
  {0x82264590, "dirty bits=8,11,17 writes=10368,10376,10548,10560,10940,10942"},
  {0x822655F0, "ring"},
  {0x8226AE78, "SetRenderState_HISTENCILWRITEENABLE"},
  {0x8226B058, "SetRenderState_ZWRITEENABLE"},
  {0x8226B848, "SetSamplerState_BORDERCOLOR"},
  {0x82272E50, "SetRenderState_HALFPIXELOFFSET"},
  {0x8227CF58, "ring"},
  {0x8227D150, "ring"},
  {0x8227F3B0, "ring"},
  {0x822869A0, "dirty bits=20 writes=10460,10940,10943,11860,11864,11868"},
  {0x82286CE8, "dirty bits= writes=32,10368,10684,12676,12680,12684"},
  {0x82286D78, "SetRenderState_ZENABLE"},
  {0x822877E8, "ring"},
  {0x82289B60, "SetRenderState_DEPTHBIAS"},
  {0x8228EF80, "ring"},
  {0x8229AB90, "SetRenderState_TESSELLATIONMODE"},
  {0x8229ABB8, "SetRenderState_STENCILPASS"},
  {0x8229F790, "SetRenderState_HIZWRITEENABLE"},
  {0x822A5EE8, "ring"},
  {0x822A6180, "SetRenderState_STENCILFUNC"},
  {0x822A61A0, "SetRenderState_HISTENCILENABLE"},
  {0x822A61C0, "ring"},
  {0x822A6558, "ring"},
  {0x822AF568, "ring"},
  {0x822B4008, "ring"},
  {0x822C07B8, "SetRenderState_WRAP8"},
  {0x822C07D8, "SetRenderState_WRAP6"},
  {0x822C0800, "SetRenderState_WRAP4"},
  {0x822C0828, "SetRenderState_WRAP2"},
  {0x822C0850, "SetRenderState_WRAP14"},
  {0x822C0878, "SetRenderState_WRAP12"},
  {0x822C08A0, "SetRenderState_WRAP10"},
  {0x822C08C8, "SetRenderState_WRAP0"},
  {0x822C08E8, "SetRenderState_STENCILMASK"},
  {0x822C0900, "SetRenderState_POINTSPRITEENABLE"},
  {0x822C0908, "SetRenderState_POINTSIZE"},
  {0x822C0950, "SetRenderState_HISTENCILREF"},
  {0x822C0968, "SetRenderState_BLENDOP"},
  {0x822C6BA8, "ring"},
  {0x822C91F0, "ring"},
  {0x822CA9B8, "dirty bits=8 writes=40,10368,10943,13172,13176"},
  {0x82A7FDE0, "ring"},
  {0x82A8AAF8, "ring"},
  {0x82A8ABB8, "ring"},
  {0x82B4E8E0, "dirty bits= writes=24"},
  {0x82B4EAF0, "dirty bits= writes="},
  {0x82B6F1D0, "ring"},
  {0x82B96E78, "SetRenderState_INVALID"},
  {0x82B96EF0, "SetRenderState_BLENDOPALPHA"},
  {0x82B96F60, "SetRenderState_SRCBLENDALPHA"},
  {0x82B96FD0, "SetRenderState_DESTBLENDALPHA"},
  {0x82B97040, "SetRenderState_SEPARATEALPHABLENDENABLE"},
  {0x82B97180, "SetRenderState_LASTPIXEL"},
  {0x82B971B8, "SetRenderState_LINEWIDTH"},
  {0x82B97228, "SetRenderState_BUFFER2FRAMES"},
  {0x82B97288, "SetRenderState_TWOSIDEDSTENCILMODE"},
  {0x82B97300, "SetRenderState_CCW_STENCILFUNC"},
  {0x82B97330, "SetRenderState_CCW_STENCILFAIL"},
  {0x82B97368, "SetRenderState_CCW_STENCILZFAIL"},
  {0x82B973A0, "SetRenderState_CCW_STENCILPASS"},
  {0x82B973E8, "SetRenderState_CCW_STENCILREF"},
  {0x82B97408, "SetRenderState_CCW_STENCILMASK"},
  {0x82B97428, "SetRenderState_CCW_STENCILWRITEMASK"},
  {0x82B97448, "SetRenderState_CLIPPLANEENABLE"},
  {0x82B97498, "SetRenderState_SCISSORTESTENABLE"},
  {0x82B974E0, "SetRenderState_MULTISAMPLEANTIALIAS"},
  {0x82B97510, "SetRenderState_MULTISAMPLEMASK"},
  {0x82B97538, "SetRenderState_COLORWRITEENABLE1"},
  {0x82B97578, "SetRenderState_COLORWRITEENABLE2"},
  {0x82B975B8, "SetRenderState_COLORWRITEENABLE3"},
  {0x82B97730, "SetRenderState_VIEWPORTENABLE"},
  {0x82B97788, "SetRenderState_HIGHPRECISIONBLENDENABLE1"},
  {0x82B97820, "SetRenderState_HIGHPRECISIONBLENDENABLE2"},
  {0x82B978B8, "SetRenderState_HIGHPRECISIONBLENDENABLE3"},
  {0x82B97950, "SetRenderState_MINTESSELLATIONLEVEL"},
  {0x82B979B8, "SetRenderState_PRIMITIVERESETENABLE"},
  {0x82B979E8, "SetRenderState_PRIMITIVERESETINDEX"},
  {0x82B97A38, "SetRenderState_GUARDBAND_X"},
  {0x82B97A68, "SetRenderState_GUARDBAND_Y"},
  {0x82B97A98, "SetRenderState_DISCARDBAND_X"},
  {0x82B97AC0, "SetRenderState_DISCARDBAND_Y"},
  {0x82B97B48, "SetRenderState_PRESENTINTERVAL"},
  {0x82B97B58, "SetRenderState_PRESENTIMMEDIATETHRESHOLD"},
  {0x82B97BB0, "SetSamplerState_MINFILTERZ"},
  {0x82B97C90, "SetSamplerState_MAGFILTERZ"},
  {0x82B97D48, "SetSamplerState_SEPARATEZFILTERENABLE"},
  {0x82B97E00, "SetSamplerState_ANISOTROPYBIAS"},
  {0x82B97EE8, "SetSamplerState_MAXMIPLEVEL"},
  {0x82B97F68, "SetSamplerState_MINMIPLEVEL"},
  {0x82B98068, "SetSamplerState_HGRADIENTEXPBIAS"},
  {0x82B980C0, "SetSamplerState_VGRADIENTEXPBIAS"},
  {0x82B98118, "SetSamplerState_WHITEBORDERCOLORW"},
  {0x82B98170, "SetSamplerState_POINTBORDERENABLE"},
  {0x82B98D28, "lib sites=0 IM_LOAD_IMMEDIATE,INVALIDATE_STATE"},
  {0x82B98F00, "lib sites=1"},
  {0x82B99018, "lib sites=0 DRAW_INDX_2"},
  {0x82B991B0, "lib sites=4"},
  {0x82B99208, "lib sites=4"},
  {0x82B99260, "lib sites=4"},
  {0x82B992B0, "lib sites=1"},
  {0x82B993C0, "lib sites=1"},
  {0x82B994B8, "lib sites=1"},
  {0x82B995A8, "dirty bits=19 writes=11820,12216,12220,12240,12244,12246"},
  {0x82B99720, "lib sites=6"},
  {0x82B997A8, "lib sites=1"},
  {0x82B997B0, "lib sites=1"},
  {0x82B9D400, "lib sites=5"},
  {0x82B9D4B8, "lib sites=4"},
  {0x82B9D4C0, "lib sites=2"},
  {0x82B9D4E0, "lib sites=3"},
  {0x82B9D4F8, "lib sites=3"},
  {0x82B9D518, "lib sites=2"},
  {0x82B9D540, "lib sites=2"},
  {0x82B9D5B8, "lib sites=2"},
  {0x82B9D638, "lib sites=3"},
  {0x82B9D6B8, "lib sites=4"},
  {0x82B9D750, "lib sites=3"},
  {0x82B9D7A8, "lib sites=3"},
  {0x82B9D840, "lib sites=3"},
  {0x82B9D8A0, "lib sites=3"},
  {0x82B9D8F8, "lib sites=3"},
  {0x82B9D958, "lib sites=3"},
  {0x82B9D970, "lib sites=4"},
  {0x82B9D988, "lib sites=3"},
  {0x82B9D990, "lib sites=3"},
  {0x82B9DA58, "lib sites=3"},
  {0x82B9DA70, "lib sites=9"},
  {0x82B9DB08, "lib sites=1"},
  {0x82B9DB70, "lib sites=3"},
  {0x82B9DB88, "lib sites=1"},
  {0x82B9DBA0, "lib sites=7"},
  {0x82B9DBD0, "lib sites=4"},
  {0x82B9DBE8, "lib sites=1"},
  {0x82B9DC60, "lib sites=4"},
  {0x82B9DCB8, "lib sites=2"},
  {0x82B9DD48, "lib sites=4"},
  {0x82B9E1F0, "lib sites=3"},
  {0x82B9E750, "lib sites=3"},
  {0x82B9E8C8, "lib sites=1"},
  {0x82B9EB48, "lib sites=5"},
  {0x82B9EE58, "lib sites=2"},
  {0x82B9EEC0, "lib sites=1"},
  {0x82B9EED0, "lib sites=1"},
  {0x82B9EEE0, "lib sites=2 DRAW_INDX_2,INVALIDATE_STATE"},
  {0x82B9F038, "lib sites=1 DRAW_INDX_2,IM_LOAD_IMMEDIATE,INVALIDATE_STATE"},
  {0x82B9F3C0, "lib sites=1"},
  {0x82B9F550, "lib sites=1"},
  {0x82B9F940, "lib sites=2"},
  {0x82B9F958, "lib sites=1"},
  {0x82B9F970, "lib sites=3"},
  {0x82B9FA98, "lib sites=7"},
  {0x82B9FCE8, "ring"},
  {0x82BA0380, "lib sites=0 REG_TO_MEM"},
  {0x82BA1A08, "lib sites=2"},
  {0x82BA1AB0, "lib sites=9"},
  {0x82BA1B78, "lib sites=1"},
  {0x82BA1C40, "lib sites=1"},
  {0x82BA1D40, "lib sites=21 SET_BIN_MASK_HI,SET_BIN_MASK_LO"},
  {0x82BA1EE0, "lib sites=3"},
  {0x82BA1FA8, "lib sites=3"},
  {0x82BA2080, "lib sites=0 IM_LOAD_IMMEDIATE,INVALIDATE_STATE"},
  {0x82BA2200, "lib sites=1"},
  {0x82BA2218, "lib sites=10"},
  {0x82BA2270, "lib sites=1"},
  {0x82BA22B0, "lib sites=1"},
  {0x82BA22C0, "lib sites=2"},
  {0x82BA22C8, "lib sites=1"},
  {0x82BA2360, "lib sites=1"},
  {0x82BA23E8, "dirty bits=19 writes=11820"},
  {0x82BA2500, "lib sites=1"},
  {0x82BA2548, "lib sites=2"},
  {0x82BA2748, "lib sites=1"},
  {0x82BA27C8, "lib sites=8"},
  {0x82BA2830, "lib sites=3 VdSetSystemCommandBufferGpuIdentifierAddress,VdInitializeRingBuffer,VdEnableRingBufferRPtrWriteBack,VdSetSystemCommandBufferGpuIdentifierAddress"},
  {0x82BA2F68, "lib sites=3 WAIT_REG_MEM"},
  {0x82BA3148, "lib sites=0 REG_RMW"},
  {0x82BA32F8, "ring"},
  {0x82BA34D8, "lib sites=3 REG_RMW VdGetSystemCommandBuffer,VdSwap,VdSetDisplayMode,VdGetCurrentDisplayInformation,VdPersistDisplay"},
  {0x82BA3D88, "lib sites=1"},
  {0x82BA40F0, "lib sites=2"},
  {0x82BA4328, "lib sites=0 VdGetCurrentDisplayGamma"},
  {0x82BA45E0, "lib sites=1"},
  {0x82BA4678, "lib sites=1"},
  {0x82BA48B0, "lib sites=0 COND_WRITE"},
  {0x82BA49B0, "lib sites=2"},
  {0x82BA4AF8, "lib sites=1"},
  {0x82BA4D80, "lib sites=0 EVENT_WRITE_SHD"},
  {0x82BA4FB8, "lib sites=0 SET_BIN_SELECT_LO"},
  {0x82BA60C8, "lib sites=1 REG_RMW"},
  {0x82BA6298, "lib sites=1"},
  {0x82BA6508, "lib sites=1 VdQueryVideoMode"},
  {0x82BA67C8, "lib sites=1"},
  {0x82BA6968, "lib sites=0 VdShutdownEngines"},
  {0x82BA6990, "lib sites=1 VdInitializeEngines,VdSetGraphicsInterruptCallback,VdIsHSIOTrainingSucceeded"},
  {0x82BA6C18, "lib sites=3 VdSetSystemCommandBufferGpuIdentifierAddress,VdSetGraphicsInterruptCallback,VdShutdownEngines"},
  {0x82BA77D0, "ring"},
  {0x82BA7898, "ring"},
  {0x82BA7928, "ring"},
  {0x82BA79D0, "ring"},
  {0x82BA7B28, "lib sites=0 DRAW_INDX_2,IM_LOAD_IMMEDIATE,INVALIDATE_STATE"},
  {0x82BA83C0, "lib sites=0 DRAW_INDX_2,IM_LOAD_IMMEDIATE,INVALIDATE_STATE"},
  {0x82BA8928, "ring"},
  {0x82BA95E0, "lib sites=0 VdQueryVideoMode"},
  {0x82BAA4C8, "ring"},
  {0x82BAA848, "lib sites=0 EVENT_WRITE_SHD"},
  {0x82BAAA28, "lib sites=0 VdEnableDisableClockGating,VdEnableDisableClockGating"},
  {0x82BABF58, "lib sites=0 VdGetCurrentDisplayInformation"},
  {0x82BAC2C8, "lib sites=0 VdGetCurrentDisplayInformation"},
  {0x82BAC718, "lib sites=0 EVENT_WRITE,IM_LOAD_IMMEDIATE,INVALIDATE_STATE"},
  {0x82BAE440, "lib sites=0 VdQueryVideoMode"},
  {0x82BAE960, "lib sites=0 VdQueryVideoFlags"},
  {0x82BAEA88, "lib sites=0 VdInitializeScalerCommandBuffer"},
  {0x82BAEC38, "lib sites=0 VdCallGraphicsNotificationRoutines"},
  {0x82BAED78, "lib sites=0 VdRetrainEDRAMWorker,VdRetrainEDRAM,VdRetrainEDRAM"},
  {0x82C6AB40, "dirty bits= writes="},
  {0x82D05868, "dirty bits= writes=40,64,304,312"},
  {0x82D05BB0, "dirty bits= writes=56,72,316,320,352"},
  {0x8304DA78, "dirty bits= writes=0,4,8,12,24,32"},
  {0x83050A98, "dirty bits= writes=0,4,8,12,24,32"},
};
std::atomic<uint64_t> g_count[kHooks];
uint64_t g_last[kHooks];
std::atomic<int> g_nsamples[kHooks];
uint32_t g_samples[kHooks][kSamples][8];
std::atomic<uint32_t> g_tick{0};
std::mutex g_dump_mutex;
auto g_t0 = std::chrono::steady_clock::now();
double g_next_dump = 10.0;

void Dump() {
  std::lock_guard<std::mutex> lock(g_dump_mutex);
  const double t = std::chrono::duration<double>(std::chrono::steady_clock::now() - g_t0).count();
  if (t < g_next_dump) return;
  g_next_dump = t + 10.0;
  REXLOG_INFO("[ngpu] census at {:.1f} s (calls total / last 10 s)", t);
  for (int i = 0; i < kHooks; ++i) {
    const uint64_t c = g_count[i].load(std::memory_order_relaxed);
    if (c == 0) continue;
    const uint64_t d = c - g_last[i];
    g_last[i] = c;
    std::string s;
    const int ns = g_nsamples[i].load(std::memory_order_acquire);
    if (ns > 0 && ns <= kSamples) {
      for (int k = 0; k < ns; ++k) {
        const uint32_t* a = g_samples[i][k];
        s += fmt::format(" [{:08X} {:08X} {:08X} {:08X} {:08X} {:08X} {:08X} {:08X}]",
                         a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7]);
      }
      // RE-ARMED after every print (it used to print once): the first samples
      // are the menu's, and identifying an entry point by its arguments needs
      // the WORLD's shapes - the clear's flags and colour, a resolve's rects.
      g_nsamples[i].store(0, std::memory_order_release);
    }
    REXLOG_INFO("[ngpu] sub_{:08X} {} calls={} +{}{}", kEntries[i].addr, kEntries[i].label, c, d, s);
  }
}

inline void Trace(int i, PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6,
                  PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) {
  // P2 attribution census (fable2_p2_census.cpp): its own switch (FABLE2_P2), independent of ngpu_trace. Hook 262 is
  // Present (sub_82BA34D8), the frame marker; 'lib ...' labels are library entry points (r3 = the device).
  if (i == 262) fable2::p2::FrameMarker(r3.u32);
  const uint32_t a8[8] = {r3.u32, r4.u32, r5.u32, r6.u32, r7.u32, r8.u32, r9.u32, r10.u32};
  fable2::p2::Enter(i, r3.u32, kEntries[i].label[0] == 'l', a8);   // a8: the source census (FABLE2_P3SRC)
  if (!REXCVAR_GET(ngpu_trace)) return;
  g_count[i].fetch_add(1, std::memory_order_relaxed);
  int ns = g_nsamples[i].load(std::memory_order_relaxed);
  if (ns < kSamples) {
    uint32_t* a = g_samples[i][ns];
    a[0] = r3.u32; a[1] = r4.u32; a[2] = r5.u32; a[3] = r6.u32;
    a[4] = r7.u32; a[5] = r8.u32; a[6] = r9.u32; a[7] = r10.u32;
    g_nsamples[i].store(ns + 1, std::memory_order_release);
  }
  if ((g_tick.fetch_add(1, std::memory_order_relaxed) & 1023) == 0) Dump();
}
}  // namespace

void ngpu_82188750(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(0, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82188770(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(1, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82188798(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(2, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821887D8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(3, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82188800(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(4, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82188828(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(5, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82188850(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(6, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82188878(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(7, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821888A0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(8, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821888C0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(9, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821888E8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(10, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82188910(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(11, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82188930(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(12, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82193008(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(13, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82196628(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(14, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82196750(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(15, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::OnResolve(r3.u32, r4.u32, r5.u32, r6.u32, r7.u32, r8.u32, r9.u32, r10.u32); }
void ngpu_8219CCC0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(16, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8219CD68(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(17, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821A1700(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(18, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821A8B88(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(19, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821A8C18(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(20, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821B1330(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(21, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821B1350(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(22, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821B6C60(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(23, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821B9A08(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(24, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821BFDF0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(25, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821C19F0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(26, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821C6478(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(27, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821C91C8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(28, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821CD310(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(29, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821DC158(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(30, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821DCAA0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(31, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821E0BF8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(32, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821E2C08(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(33, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821E5290(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(34, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821E56F8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(35, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821EC798(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(36, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821EFAC0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(37, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821F0490(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(38, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821F0E00(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(39, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821F6270(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(40, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821F6300(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(41, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821F9918(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(42, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_821F9D00(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(43, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82202D10(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(44, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82205F68(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(45, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82206888(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(46, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::OnResolveXdk(r3.u32, r4.u32, r5.u32, r6.u32, r7.u32, r8.u32, r9.u32, r10.u32); }
void ngpu_82207AF8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(47, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82208020(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(48, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82208BB0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(49, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::OnSetShader(r3.u32, r4.u32, 0); }
void ngpu_8220A490(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(50, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8220B470(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(51, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8220BD40(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(52, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82213AD8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(53, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82215488(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(54, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822154B0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(55, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82217DB8(PPCRegister& r1, PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(56, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::OnDrawUP(r3.u32, r4.u32, r5.u32, r6.u32, r7.u32, r8.u32, r9.u32, r10.u32, r1.u32); }
void ngpu_822192E8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(57, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::OnSetRenderTarget(r3.u32, r4.u32, r5.u32); }
void ngpu_822194B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(58, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8221AE18(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(59, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8221B010(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(60, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8221C3E8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(61, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::OnDrawVertices(r3.u32, r4.u32, r5.u32, r6.u32); }
void ngpu_8221C898(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(62, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8221D190(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(63, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8221D1B0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(64, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8221DFC0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(65, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::OnDrawIndexed(r3.u32, r4.u32, r5.u32, r6.u32, r7.u32); }
void ngpu_8221E410(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(66, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82221740(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(67, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82221858(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(68, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::OnSetShader(r3.u32, r4.u32, r5.u32); }
void ngpu_82221B90(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(69, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::OnLoadConstants(r3.u32, r4.u32, r5.u32, r6.u32, r7.u32); }
void ngpu_822224A8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(70, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82223B50(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(71, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82225E08(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(72, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8222B8F0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(73, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8222BFA0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(74, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8222C568(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(75, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8222C818(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(76, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82232510(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(77, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::OnSetShader(r3.u32, r4.u32, 0); }
void ngpu_822373F0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(78, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82238128(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(79, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822383A0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(80, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822398D0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(81, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82239910(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(82, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8223B130(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(83, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82242668(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(84, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82264590(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(85, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822655F0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(86, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8226AE78(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(87, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8226B058(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(88, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8226B848(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(89, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82272E50(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(90, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8227CF58(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(91, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8227D150(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(92, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8227F3B0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(93, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822869A0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(94, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82286CE8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(95, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82286D78(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(96, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822877E8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(97, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82289B60(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(98, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8228EF80(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(99, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8229AB90(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(100, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8229ABB8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(101, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8229F790(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(102, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822A5EE8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(103, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822A6180(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(104, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822A61A0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(105, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822A61C0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(106, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822A6558(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(107, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822AF568(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(108, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822B4008(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(109, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C07B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(110, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C07D8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(111, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C0800(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(112, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C0828(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(113, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C0850(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(114, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C0878(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(115, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C08A0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(116, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C08C8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(117, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C08E8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(118, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C0900(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(119, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C0908(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(120, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C0950(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(121, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C0968(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(122, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C6BA8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(123, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822C91F0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(124, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_822CA9B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(125, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82A7FDE0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(126, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82A8AAF8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(127, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82A8ABB8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(128, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B4E8E0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(129, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B4EAF0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(130, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B6F1D0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(131, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B96E78(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(132, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B96EF0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(133, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B96F60(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(134, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B96FD0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(135, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97040(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(136, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97180(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(137, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B971B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(138, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97228(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(139, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97288(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(140, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97300(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(141, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97330(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(142, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97368(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(143, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B973A0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(144, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B973E8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(145, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97408(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(146, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97428(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(147, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97448(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(148, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97498(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(149, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B974E0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(150, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97510(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(151, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97538(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(152, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97578(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(153, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B975B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(154, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97730(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(155, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97788(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(156, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97820(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(157, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B978B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(158, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97950(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(159, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B979B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(160, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B979E8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(161, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97A38(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(162, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97A68(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(163, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97A98(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(164, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97AC0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(165, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97B48(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(166, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97B58(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(167, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97BB0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(168, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97C90(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(169, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97D48(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(170, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97E00(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(171, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97EE8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(172, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B97F68(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(173, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B98068(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(174, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B980C0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(175, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B98118(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(176, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B98170(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(177, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B98D28(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(178, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B98F00(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(179, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B99018(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(180, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::NoteLibraryDraw(2, r3.u32, r4.u32, r5.u32); }
void ngpu_82B991B0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(181, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B99208(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(182, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B99260(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(183, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B992B0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(184, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B993C0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(185, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B994B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(186, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B995A8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(187, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B99720(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(188, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B997A8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(189, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B997B0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(190, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D400(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(191, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D4B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(192, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D4C0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(193, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D4E0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(194, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D4F8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(195, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D518(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(196, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D540(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(197, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D5B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(198, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D638(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(199, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D6B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(200, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D750(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(201, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D7A8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(202, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D840(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(203, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D8A0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(204, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D8F8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(205, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D958(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(206, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D970(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(207, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D988(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(208, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9D990(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(209, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9DA58(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(210, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9DA70(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(211, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9DB08(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(212, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9DB70(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(213, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9DB88(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(214, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9DBA0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(215, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9DBD0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(216, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9DBE8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(217, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9DC60(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(218, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9DCB8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(219, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9DD48(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(220, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9E1F0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(221, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9E750(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(222, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9E8C8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(223, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9EB48(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(224, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9EE58(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(225, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9EEC0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(226, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9EED0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(227, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9EEE0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(228, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::NoteLibraryDraw(0, r3.u32, r4.u32, r5.u32); }
void ngpu_82B9F038(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(229, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::NoteLibraryDraw(1, r3.u32, r4.u32, r5.u32); }
void ngpu_82B9F3C0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(230, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9F550(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(231, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9F940(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(232, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9F958(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(233, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9F970(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(234, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9FA98(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(235, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82B9FCE8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(236, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA0380(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(237, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA1A08(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(238, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA1AB0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(239, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA1B78(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(240, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA1C40(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(241, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA1D40(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(242, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA1EE0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(243, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA1FA8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(244, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA2080(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(245, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA2200(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(246, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA2218(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(247, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA2270(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(248, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA22B0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(249, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA22C0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(250, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA22C8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(251, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA2360(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(252, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA23E8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(253, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA2500(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(254, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA2548(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(255, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA2748(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(256, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA27C8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(257, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA2830(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(258, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA2F68(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(259, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA3148(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(260, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA32F8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(261, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA34D8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(262, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::OnPresent(r3.u32); }
void ngpu_82BA3D88(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(263, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA40F0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(264, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA4328(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(265, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA45E0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(266, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA4678(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(267, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA48B0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(268, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA49B0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(269, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA4AF8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(270, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA4D80(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(271, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA4FB8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(272, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA60C8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(273, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA6298(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(274, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA6508(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(275, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA67C8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(276, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA6968(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(277, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA6990(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(278, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA6C18(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(279, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA77D0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(280, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA7898(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(281, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA7928(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(282, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA79D0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(283, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA7B28(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(284, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::NoteLibraryDraw(3, r3.u32, r4.u32, r5.u32); }
void ngpu_82BA83C0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(285, r3, r4, r5, r6, r7, r8, r9, r10); ngpu::NoteLibraryDraw(4, r3.u32, r4.u32, r5.u32); }
void ngpu_82BA8928(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(286, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BA95E0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(287, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BAA4C8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(288, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BAA848(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(289, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BAAA28(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(290, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BABF58(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(291, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BAC2C8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(292, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BAC718(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(293, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BAE440(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(294, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BAE960(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(295, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BAEA88(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(296, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BAEC38(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(297, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82BAED78(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(298, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82C6AB40(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(299, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82D05868(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(300, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_82D05BB0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(301, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_8304DA78(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(302, r3, r4, r5, r6, r7, r8, r9, r10); }
void ngpu_83050A98(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { Trace(303, r3, r4, r5, r6, r7, r8, r9, r10); }

// Hand-added (not from the generator): DrawIndexedVertices' exit at 0x8221E408, after the XDK wrote the draw's packets.
void ngpu_8221E408(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { (void)r4; (void)r5; (void)r6; (void)r7; (void)r8; (void)r9; (void)r10; ngpu::OnDrawIndexedDone(r3.u32); }

// Hand-added: DrawVertices' exit at 0x8221C7D0, after the XDK wrote the draw's packets.
void ngpu_8221C7D0(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { (void)r4; (void)r5; (void)r6; (void)r7; (void)r8; (void)r9; (void)r10; ngpu::OnDrawVerticesDone(r3.u32); }

// Hand-added: DrawIndexedVerticesUP's exit at 0x822182CC (addi r1,r1,224; r3 = the HRESULT), after the XDK wrote the draw's packets.
void ngpu_822182CC(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { (void)r4; (void)r5; (void)r6; (void)r7; (void)r8; (void)r9; (void)r10; ngpu::OnDrawUPDone(r3.u32); }

// Hand-added: the DrawIndexedVerticesUP wrapper sub_8222E120 (entry, r1 for the stride on the stack) and its exit at 0x8222E1B8 (addi r1,r1,176).
void ngpu_8222E120(PPCRegister& r1, PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { ngpu::OnDrawUPBegin(r3.u32, r4.u32, r5.u32, r6.u32, r7.u32, r8.u32, r9.u32, r10.u32, r1.u32); }
void ngpu_8222E1B8(PPCRegister& r3, PPCRegister& r4, PPCRegister& r5, PPCRegister& r6, PPCRegister& r7, PPCRegister& r8, PPCRegister& r9, PPCRegister& r10) { (void)r4; (void)r5; (void)r6; (void)r7; (void)r8; (void)r9; (void)r10; ngpu::OnDrawUPEnd(r3.u32); }
